//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A8: return "BOOST (PA8)";
		case Gpio::B6: return "VSS (PB6)";
		case Gpio::B7: return "FAN (PB7)";
		case Gpio::B8: return "IDLE2 (PB8)";
		case Gpio::B9: return "IDLE1 (PB9)";
		case Gpio::C13: return "MAIN_RLY (PC13)";
		case Gpio::D0: return "CAN_RX (PD0)";
		case Gpio::D1: return "CAN_TX (PD1)";
		case Gpio::D10: return "INJ3 (PD10)";
		case Gpio::D11: return "INJ4 (PD11)";
		case Gpio::D12: return "INJ5 (PD12)";
		case Gpio::D13: return "INJ6 (PD13)";
		case Gpio::D14: return "INJ7 (PD14)";
		case Gpio::D15: return "INJ8 (PD15)";
		case Gpio::D2: return "SD_CS (PD2)";
		case Gpio::D3: return "CRANK (PD3)";
		case Gpio::D4: return "CAM (PD4)";
		case Gpio::D5: return "CEL (PD5)";
		case Gpio::D7: return "TACHO (PD7)";
		case Gpio::D8: return "INJ1 (PD8)";
		case Gpio::D9: return "INJ2 (PD9)";
		case Gpio::E0: return "IGN1 (PE0)";
		case Gpio::E1: return "IGN2 (PE1)";
		case Gpio::E10: return "A/C_RLY (PE10)";
		case Gpio::E11: return "FUEL_PUMP (PE11)";
		case Gpio::E12: return "IN1 (PB12)";
		case Gpio::E13: return "IN2 (PB13)";
		case Gpio::E14: return "IN3 (PB14)";
		case Gpio::E15: return "LAUNCH (PE15)";
		case Gpio::E2: return "IGN3 (PE2)";
		case Gpio::E3: return "IGN4 (PE3)";
		case Gpio::E4: return "IGN5 (PE4)";
		case Gpio::E5: return "IGN6 (PE5)";
		case Gpio::E6: return "IGN7 (PE6)";
		case Gpio::E7: return "IGN8 (PE7)";
		case Gpio::E9: return "A/C_SW (PE9)";
		default: return nullptr;
	}
	return nullptr;
}
